app = "nummus-api"
primary_region = "gru"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"
  API_BASE_URL = "https://nummus-api.fremez.com"
  WEB_APP_BASE_URL = "https://nummus.fremez.com"
  FRONTEND_URL = "https://nummus.fremez.com"
  BETTER_AUTH_URL = "https://nummus-api.fremez.com"

# Roda as migrations do Prisma antes de cada release
release_command = "pnpm prisma migrate deploy"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
